dataset:
  data_path: data/train.csv
  seq_len: 512
  split_ratio: 0.2
  batch_size: 4
model:
  num_op: 3
  dropout: 0.2
optimizer:
  name: adam
  hparams:
    lr: 0.0001
training:
  max_epochs: 2
  early_stop_count: 10
  chkp_path: "bert_weights.pt"  
